spring.application.name=producto
server.port=8082

# Conexión Oracle con Wallet
spring.datasource.url=jdbc:oracle:thin:@ecommerce_high?TNS_ADMIN=C:/Users/carol.LAPTOP-EKTSPIVV.000/Downloads/producto/producto/src/main/resources/wallet
spring.datasource.username=PRODUCTO_USER
spring.datasource.password=Productouser123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
